-- ============================================================================
-- Gahoi Portal — Seed: Akna List (222 verified entries)
-- मौजूदा Code.gs के INITIAL_AKNAS array से programmatically निकाला गया —
-- हाथ से टाइप नहीं किया, इसलिए transcription-error का खतरा नहीं
-- ============================================================================

insert into akna_list (hindi, english, variants, added_by) values
  ('रूसिया', 'rusia', 'rusia rusiya', 'system'),
  ('अरुसिया', 'arusia', 'arusia arusiya', 'system'),
  ('बेहरे', 'behre', 'behre behr', 'system'),
  ('पहारिया', 'pahariya', 'pahariya pahari', 'system'),
  ('रेजा', 'reja', 'reja', 'system'),
  ('मर', 'mar', 'mar', 'system'),
  ('मोर', 'mor', 'mor', 'system'),
  ('मोदी', 'modi', 'modi', 'system'),
  ('सेठिया', 'sethiya', 'sethiya sethi', 'system'),
  ('दमेले', 'damele', 'damele damel', 'system'),
  ('कठल', 'kathal', 'kathal kathl', 'system'),
  ('मरेले', 'marele', 'marele marel', 'system'),
  ('नाहर', 'nahar', 'nahar', 'system'),
  ('कारेखेमऊ', 'karekhamau', 'karekhamau karekhe', 'system'),
  ('रघारे', 'raghare', 'raghare raghar', 'system'),
  ('टुड़हा', 'tudha', 'tudha turha', 'system'),
  ('साह', 'sah', 'sah', 'system'),
  ('साव', 'sav', 'sav saw', 'system'),
  ('कसाव', 'kasav', 'kasav kasaw', 'system'),
  ('खैरा', 'khaira', 'khaira khera', 'system'),
  ('धूसर', 'dhusar', 'dhusar dhoosar', 'system'),
  ('सहदेले', 'sahdele', 'sahdele sahd', 'system'),
  ('ददरया', 'dadarya', 'dadarya dadry', 'system'),
  ('चुनगेले', 'chungele', 'chungele chungel', 'system'),
  ('सरावगी', 'sarawagi', 'sarawagi sarogi', 'system'),
  ('पटोदिया', 'patodiya', 'patodiya patodi', 'system'),
  ('पटेरहा', 'paterha', 'paterha paterh', 'system'),
  ('खरया', 'kharya', 'kharya', 'system'),
  ('बरया', 'barya', 'barya', 'system'),
  ('कुनयार', 'kunyar', 'kunyar kuniyar', 'system'),
  ('पूरनपुरिया', 'puranpuriya', 'puranpuriya pooranpuri', 'system'),
  ('झांझर', 'jhanjhar', 'jhanjhar jhanjh', 'system'),
  ('बागर', 'bagar', 'bagar', 'system'),
  ('सेठ', 'seth', 'seth', 'system'),
  ('छिरोल्या', 'chiroliya', 'chiroliya chirolay', 'system'),
  ('तरसोलिया', 'tarsoliya', 'tarsoliya tarsoli', 'system'),
  ('जकोन्या', 'jakonya', 'jakonya jakon', 'system'),
  ('कन्थरिया', 'kanthariya', 'kanthariya kanthari', 'system'),
  ('कटारे', 'katare', 'katare katar', 'system'),
  ('जौरिया', 'jauriya', 'jauriya jauri', 'system'),
  ('इटोरिया', 'itoriya', 'itoriya itori', 'system'),
  ('कुरेले', 'kurele', 'kurele kurel', 'system'),
  ('विलैया', 'vilaiya', 'vilaiya vilai', 'system'),
  ('बड़ेरिया', 'bareriya', 'bareriya baderi', 'system'),
  ('निगोती', 'nigoti', 'nigoti', 'system'),
  ('सोनी', 'soni', 'soni', 'system'),
  ('रावत', 'rawat', 'rawat raut', 'system'),
  ('ब्रिजपुरिया', 'brijpuriya', 'brijpuriya brijpuri', 'system'),
  ('गन्धी', 'gandhi', 'gandhi gandi', 'system'),
  ('सिजरिया', 'sijariya', 'sijariya sijari', 'system'),
  ('बमोरिया', 'bamoriya', 'bamoriya bamori', 'system'),
  ('दोहरिया', 'dohariya', 'dohariya dohari', 'system'),
  ('देवरहा', 'dewarha', 'dewarha dewrha', 'system'),
  ('मुनगेले', 'mungele', 'mungele mungel', 'system'),
  ('कुरोठिया', 'kurothiya', 'kurothiya kurothi', 'system'),
  ('भगोरया', 'bhagorya', 'bhagorya bhagory', 'system'),
  ('हडयाल', 'hadyal', 'hadyal', 'system'),
  ('बेद', 'bed', 'bed ved', 'system'),
  ('बरदिया', 'bardiya', 'bardiya bardi', 'system'),
  ('मिहोनिया', 'mihoniya', 'mihoniya mihoni', 'system'),
  ('दिगोरिया', 'digoriya', 'digoriya digori', 'system'),
  ('जार', 'jar', 'jar', 'system'),
  ('पटवारी', 'patwari', 'patwari patwar', 'system'),
  ('गंधी', 'gandhi', 'gandhi gandi', 'system'),
  ('गेडा', 'geda', 'geda', 'system'),
  ('चपरा', 'chapra', 'chapra', 'system'),
  ('नोगरैया', 'nogaraiya', 'nogaraiya nograiya', 'system'),
  ('झुड़ेले', 'jhudele', 'jhudele jhudel', 'system'),
  ('डेंगरे', 'dengre', 'dengre denger', 'system'),
  ('बरेले', 'barele', 'barele barel', 'system'),
  ('नौलहा', 'naulaha', 'naulaha naulh', 'system'),
  ('साब', 'sab', 'sab', 'system'),
  ('पटरैया', 'patraiya', 'patraiya patrai', 'system'),
  ('बरहा', 'barha', 'barha', 'system'),
  ('हथनोरिया', 'hathnoriya', 'hathnoriya hathnori', 'system'),
  ('दमोरहा', 'damorha', 'damorha', 'system'),
  ('लखटकिया', 'lakhatkiya', 'lakhatkiya lakhatki', 'system'),
  ('पहारू', 'paharu', 'paharu', 'system'),
  ('दगरिहा', 'dagariha', 'dagariha', 'system'),
  ('कुरेटिया', 'kuretiya', 'kuretiya kureti', 'system'),
  ('गुगोरिया', 'gugoriya', 'gugoriya gugori', 'system'),
  ('जुगोरिया', 'jugoriya', 'jugoriya jugori', 'system'),
  ('सुलगनिया', 'sulagniya', 'sulagniya sulagni', 'system'),
  ('सावला', 'sawla', 'sawla savla', 'system'),
  ('वगेरिया', 'vageriya', 'vageriya vageri', 'system'),
  ('नीखरा', 'nikhra', 'nikhra neekh', 'system'),
  ('इन्दुरख्या', 'indurkya', 'indurkya indurkhya', 'system'),
  ('कस्तवार', 'kastawar', 'kastawar kastwar', 'system'),
  ('मिसुरहा', 'misurha', 'misurha', 'system'),
  ('विसवारी', 'viswari', 'viswari bistwari', 'system'),
  ('पिपरसानिया', 'piparsaniya', 'piparsaniya piparsa', 'system'),
  ('नाछोला', 'nachola', 'nachola', 'system'),
  ('बड़ोन्या', 'baronya', 'baronya badony', 'system'),
  ('बिनौरया', 'binaurya', 'binaurya binaury', 'system'),
  ('इकसड़े', 'iksade', 'iksade', 'system'),
  ('सुलगहनया', 'sulganaya', 'sulganaya sulgana', 'system'),
  ('कंजौल्या', 'kanjaulya', 'kanjaulya kanjol', 'system'),
  ('निगोतिया', 'nigotiya', 'nigotiya', 'system'),
  ('नगरिया', 'nagariya', 'nagariya nagari', 'system'),
  ('रिखोल्या', 'rikholya', 'rikholya rikhol', 'system'),
  ('लखौरया', 'lakhaurya', 'lakhaurya', 'system'),
  ('शिपौल्या', 'shipaulya', 'shipaulya shipol', 'system'),
  ('लहारिया', 'lahariya', 'lahariya lahari', 'system'),
  ('सिरोजिया', 'sirojiya', 'sirojiya siroji', 'system'),
  ('कुचिया', 'kuchiya', 'kuchiya kuchi', 'system'),
  ('टिकरया', 'tikarya', 'tikarya', 'system'),
  ('बरसैंया', 'barsaiya', 'barsaiya barsain', 'system'),
  ('तपा', 'tapa', 'tapa', 'system'),
  ('मातेले', 'matele', 'matele matel', 'system'),
  ('हुँका', 'hunka', 'hunka huka', 'system'),
  ('धनोरिया', 'dhanoriya', 'dhanoriya dhanori', 'system'),
  ('इटोदिया', 'itodiya', 'itodiya itodi', 'system'),
  ('सकेरे', 'sakere', 'sakere saker', 'system'),
  ('खड़सरिया', 'khadarsariya', 'khadarsariya khadarsa', 'system'),
  ('बढ़िया', 'badhiya', 'badhiya badhi', 'system'),
  ('विनौरया', 'vinaurya', 'vinaurya vinaury', 'system'),
  ('सिरसोनिया', 'sirsoniya', 'sirsoniya sirsoni', 'system'),
  ('खांगट', 'khangat', 'khangat', 'system'),
  ('शिकोल्या', 'shikolya', 'shikolya shikol', 'system'),
  ('तुसेले', 'tusele', 'tusele tusel', 'system'),
  ('भोंदिया', 'bhondiya', 'bhondiya bhondi', 'system'),
  ('अमौरिया', 'amauriya', 'amauriya amauri', 'system'),
  ('कुदरया', 'kudarya', 'kudarya', 'system'),
  ('खर्द', 'khard', 'khard', 'system'),
  ('सोहाने', 'sohane', 'sohane sohan', 'system'),
  ('सुहाने', 'suhane', 'suhane suhan', 'system'),
  ('तीतबिलासी', 'titbilasi', 'titbilasi titbila', 'system'),
  ('घुरा', 'ghura', 'ghura', 'system'),
  ('बजरंगगडिया', 'bajranggadiya', 'bajranggadiya bajrang', 'system'),
  ('नैना', 'naina', 'naina', 'system'),
  ('पचनोले', 'pachnole', 'pachnole pachno', 'system'),
  ('चन्दैया', 'chandaiya', 'chandaiya chandai', 'system'),
  ('कन्देले', 'kandele', 'kandele kandel', 'system'),
  ('लोहिया', 'lohiya', 'lohiya lohi', 'system'),
  ('शाव', 'shav', 'shav', 'system'),
  ('झूके', 'jhuke', 'jhuke jhuk', 'system'),
  ('आसू', 'aasu', 'aasu asu', 'system'),
  ('खंताल', 'khantal', 'khantal', 'system'),
  ('बेडर', 'bedar', 'bedar bedr', 'system'),
  ('सुदीपा', 'sudipa', 'sudipa sudeep', 'system'),
  ('आसुदीपा', 'asudipa', 'asudipa asudeep', 'system'),
  ('दीपा', 'deepa', 'deepa dipa', 'system'),
  ('शाह', 'shah', 'shah', 'system'),
  ('पचरौल्या', 'pachraulya', 'pachraulya pachrol', 'system'),
  ('चुपरा', 'chupra', 'chupra', 'system'),
  ('सकोरया', 'sakorya', 'sakorya', 'system'),
  ('छावला', 'chhawla', 'chhawla chhawal', 'system'),
  ('साहु', 'sahu', 'sahu', 'system'),
  ('कठिल', 'khatil', 'khatil kathil', 'system'),
  ('महतेले', 'mahatele', 'mahatele mahtel', 'system'),
  ('रिसौनिया', 'risauniya', 'risauniya risauni', 'system'),
  ('सादेले', 'sadele', 'sadele sadel', 'system'),
  ('जोलिया', 'joliya', 'joliya joli', 'system'),
  ('जालौन्या', 'jalaunya', 'jalaunya jaloun', 'system'),
  ('सिजारिया', 'sijariya', 'sijariya sijari', 'system'),
  ('अमोरिया', 'amoriya', 'amoriya amori', 'system'),
  ('डेवढीया', 'devdhiya', 'devdhiya devdhi', 'system'),
  ('मनगोले', 'mangole', 'mangole mangol', 'system'),
  ('मौनया', 'maunya', 'maunya maun', 'system'),
  ('बर्घिया', 'barghiya', 'barghiya barghi', 'system'),
  ('ढीगौरिया', 'dhigauriya', 'dhigauriya dhigauri', 'system'),
  ('क्षुरेले', 'kshurel', 'kshurel kshurele', 'system'),
  ('बरोल', 'barol', 'barol', 'system'),
  ('हथनोटिया', 'hatnotiya', 'hatnotiya hatnoti', 'system'),
  ('कुरैठिया', 'kuraithiya', 'kuraithiya kuraithi', 'system'),
  ('उगोरिया', 'ugoriya', 'ugoriya ugori', 'system'),
  ('साउला', 'saula', 'saula saul', 'system'),
  ('खरहा', 'kharha', 'kharha', 'system'),
  ('टपकले', 'tapakle', 'tapakle tapkal', 'system'),
  ('सकहेरे', 'sakahere', 'sakahere sakaher', 'system'),
  ('खरसडिया', 'kharsadiya', 'kharsadiya kharsadi', 'system'),
  ('झूड', 'jhud', 'jhud', 'system'),
  ('जुरेले', 'jurele', 'jurele jurel', 'system'),
  ('आसूपी', 'asupi', 'asupi asoop', 'system'),
  ('आसूती', 'asuti', 'asuti asoot', 'system'),
  ('बाडिल', 'badil', 'badil baadil', 'system'),
  ('बैडाल', 'baidal', 'baidal baidaal', 'system'),
  ('टीपा', 'tipa', 'tipa teep', 'system'),
  ('तीपा', 'tipa', 'tipa teep', 'system'),
  ('झूंक', 'jhunk', 'jhunk jhoonk', 'system'),
  ('नेहना', 'nehna', 'nehna nehan', 'system'),
  ('तीतबिरासी', 'titbirasi', 'titbirasi titbira', 'system'),
  ('भोंदू', 'bhondu', 'bhondu bhond', 'system'),
  ('मसौरया', 'masaurya', 'masaurya masaury', 'system'),
  ('मिसुरया', 'misurya', 'misurya misury', 'system'),
  ('मिही के कुंवर', 'mihi', 'mihi ke kunwar', 'system'),
  ('चौदा', 'chauda', 'chauda chaud', 'system'),
  ('चोदहा', 'chodaha', 'chodaha chodah', 'system'),
  ('बिलैया', 'bilaiya', 'bilaiya bilai', 'system'),
  ('चऊदा', 'chauda', 'chauda chaud', 'system'),
  ('सिपौल्या', 'sipaulya', 'sipaulya sipaul', 'system'),
  ('बहरे', 'behre', 'behre behr', 'system'),
  ('नार', 'nar', 'nar', 'system'),
  ('साहदेले', 'sahdele', 'sahdele sahd', 'system'),
  ('चंगेले', 'changele', 'changele changel', 'system'),
  ('पाटोदी', 'patodi', 'patodi', 'system'),
  ('पुरपुरिया', 'puranpuriya', 'puranpuriya', 'system'),
  ('कजार', 'kajar', 'kajar', 'system'),
  ('त्रिसोलिया', 'trisoliya', 'trisoliya trisoli', 'system'),
  ('खैरया', 'khaira', 'khaira khera', 'system'),
  ('सकहरे', 'sakahere', 'sakahere sakaher', 'system'),
  ('निसुंगे', 'nisunge', 'nisunge nisung', 'system'),
  ('निसूरी', 'nisuri', 'nisuri nisoor', 'system'),
  ('डांगरे', 'dangre', 'dangre danger', 'system'),
  ('निलहा', 'nilha', 'nilha', 'system'),
  ('साहू', 'sahu', 'sahu', 'system'),
  ('चउदा', 'chauda', 'chauda chaud', 'system'),
  ('बरेहे', 'barehe', 'barehe bareh', 'system'),
  ('कुचहा', 'kuchaha', 'kuchaha kuchah', 'system'),
  ('टिकरया टपकले', 'tikarya', 'tikarya tapakle', 'system'),
  ('कनकने', 'kankane', 'kankane kanak', 'system'),
  ('अमौल्या', 'amaulya', 'amaulya amaul', 'system'),
  ('झड़', 'jhard', 'jhard jhad', 'system'),
  ('डागरे', 'dagre', 'dagre dager', 'system'),
  ('चन्द्रसेनिया', 'chandraseniya', 'chandraseniya chandrasen', 'system'),
  ('झंक', 'jhank', 'jhank', 'system'),
  ('लोइया', 'loiya', 'loiya loi', 'system'),
  ('बर्षिया', 'barshiya', 'barshiya barshi', 'system'),
  ('अमरोहा', 'amroha', 'amroha', 'system'),
  ('डाडम', 'dadam', 'dadam', 'system'),
  ('सुलगानियाँ', 'sulagniya', 'sulagniya sulagni', 'system'),
  ('सुलगहनाया', 'sulganaiya', 'sulganaiya sulganai', 'system')
on conflict do nothing;
