#!/usr/bin/env node
// ============================================================================
// migrate-members.js
//
// पुराने "Members" Google Sheet का CSV export लेकर नए Postgres `persons` table के
// लिए SQL INSERT statements बनाता है। (भाग 9.15 Phase 6 "Trial Migration" का
// पहला concrete step — अभी तक सिर्फ़ योजना थी, GR के कहने पर अब असली script बनी।)
//
// इस्तेमाल:
//   1. Google Sheets में Members sheet खोलें → File → Download → CSV
//   2. उस file को यहीं इस folder में members-export.csv नाम से रखें
//      (या कोई भी नाम — नीचे कमांड में बताएं)
//   3. node migrate-members.js members-export.csv > 0009_migrated_members.sql
//   4. बना हुआ .sql file review करें, फिर Supabase पर चलाएं
//
// ⚠️ जान-बूझकर SQL-file बनाता है, सीधे DB से नहीं जुड़ता — ताकि GR/Admin असली
// migration से पहले हर पंक्ति review कर सकें (भाग 9.15 का "Data Reconciliation"
// सिद्धांत — कुछ भी बिना verify किए production में नहीं जाना)।
//
// ⚠️ Password Migration नोट (भाग 1.7 से): पुराने plaintext passwords यहाँ कहीं
// कॉपी नहीं होते — किसी को भी नहीं। auth_uid जान-बूझकर हमेशा NULL रहता है, इसे
// एक अलग "create-auth-users.js" script (नीचे बताया गया) से Supabase Admin API
// से बनाना होगा, हर member को password-reset-email भेजते हुए।
// ============================================================================

const fs = require("fs");
const { parseCsv, sqlStr, sqlBool, sqlArray, sqlJsonb, assignGahoiIdsForRows, sanitizeMMDD } = require("./_lib/csv-utils");
// ↑ CSV-parsing और SQL-escape helpers अब scripts/_lib/csv-utils.js में — इसे
// migrate-matrimony.js और migrate-mahasabha.js भी इस्तेमाल करती हैं, ताकि
// GahoiId-assignment जैसी नाज़ुक logic सिर्फ़ एक जगह रहे (देखें उस file का
// शीर्ष-कमेंट — क्यों यह ज़रूरी है)।

// ---------------------------------------------------------------------------
// मौजूदा Members sheet का headers-order (getMemberSheet() से, Code.gs)
// ---------------------------------------------------------------------------
const EXPECTED_HEADERS = [
  "Timestamp", "Name", "Father", "Mobile", "Email", "Profession", "Designation",
  "Address", "City", "Pincode", "Native", "Akna", "Birthday", "Anniversary",
  "Status", "Role", "Marital", "Spouse", "ShowMobile", "Keywords", "Photo",
  "BloodGroup", "Password", "ApprovedBy", "ApprovedAt", "StreetAddress", "Locality",
  "Landmark", "LinkedIn", "Twitter", "Instagram", "Facebook", "Hobbies",
  "School", "About", "PrivacySettings", "PublicUrlEnabled", "ProfileTier",
  "CompletionPercent", "GahoiId", "ReferredBy", "KnownMembers",
];

function main() {
  const inputFile = process.argv[2];
  if (!inputFile) {
    console.error("Usage: node migrate-members.js <members-export.csv>");
    process.exit(1);
  }

  const csv = fs.readFileSync(inputFile, "utf-8");
  const rows = parseCsv(csv);
  const headers = rows[0].map((h) => h.trim());
  const dataRows = rows.slice(1);

  // Header-order मेल खाता है या नहीं — मेल न खाने पर भी काम करेगा (नाम से column ढूंढेगा),
  // पर warning ज़रूर देगा ताकि कोई गुम column ना छूट जाए
  const missing = EXPECTED_HEADERS.filter((h) => !headers.includes(h));
  if (missing.length) {
    console.error("⚠️  ये headers CSV में नहीं मिले (SQL में NULL जाएंगे):", missing.join(", "));
  }

  const idx = (name) => headers.indexOf(name);
  const get = (row, name) => (idx(name) >= 0 ? row[idx(name)] : "");

  // ── GahoiId collision-fix ─────────────────────────────────────────────────
  // ⚠️ असल Postgres पर टेस्ट करते हुए एक genuine bug मिला: अगर कुछ rows का GahoiId
  // पहले से है (explicit) और कुछ का नहीं (DB का DEFAULT/sequence इस्तेमाल होता),
  // तो explicit insert sequence को आगे नहीं बढ़ाता — इसलिए auto-generate वाली row
  // उसी GahoiId से टकरा सकती है जो अभी-अभी explicit रूप से इस्तेमाल हुआ था,
  // "on conflict do nothing" चुपचाप उसे skip कर देता है (data silently गुम)।
  // Fix: हर row का GahoiId यहीं script में तय करें, DB के DEFAULT पर कभी निर्भर न रहें।
  // (assignGahoiIdsForRows _lib में — matrimony/mahasabha migration को भी ठीक
  // यही IDs मिलने ज़रूरी हैं, इसलिए logic अब shared है)
  const assignedGahoiIds = assignGahoiIdsForRows(dataRows, get);

  console.log("-- ============================================================================");
  console.log(`-- Auto-generated by migrate-members.js — ${dataRows.length} rows from ${inputFile}`);
  console.log("-- चलाने से पहले पूरा review करें। auth_uid जान-बूझकर हमेशा NULL है —");
  console.log("-- असली auth-account बनाने के लिए अलग create-auth-users.js चलाना होगा।");
  console.log("-- ============================================================================\n");

  let skipped = 0;
  dataRows.forEach((row, i) => {
    const name = get(row, "Name");
    if (!name || !name.trim()) { skipped++; return; }   // खाली row छोड़ें

    const gahoiId = assignedGahoiIds[i];
    const profile = {
      streetAddress: get(row, "StreetAddress") || "",
      locality: get(row, "Locality") || "",
      landmark: get(row, "Landmark") || "",
      linkedin: get(row, "LinkedIn") || "",
      twitter: get(row, "Twitter") || "",
      instagram: get(row, "Instagram") || "",
      facebook: get(row, "Facebook") || "",
      hobbies: get(row, "Hobbies") || "",
      school: get(row, "School") || "",
      bio: get(row, "About") || "",
    };
    let privacySettings = {};
    try { privacySettings = JSON.parse(get(row, "PrivacySettings") || "{}"); } catch { /* पुराना data कभी-कभी खाली/malformed होता है */ }

    // gahoi_id दे सकते हैं तो explicit रखें (पुराना GahoiId बरकरार रहे — नए sequence से
    // टकराव ना हो इसके लिए बाद में sequence को max+1 पर set करना होगा, नीचे नोट देखें)
    // gahoi_id अब हमेशा explicit (assignGahoiId से) — DB के DEFAULT पर कभी निर्भर नहीं,
    // इसलिए collision का सवाल ही नहीं उठता (ऊपर का नोट देखें)
    const cols = [
      "gahoi_id", "name", "father", "mobile", "email", "profession",
      "designation", "address", "city", "pincode", "native", "akna", "bday", "anni",
      "status", "role", "marital", "spouse", "show_mobile", "keywords", "photo",
      "blood_group", "referred_by", "approved_by", "approved_at", "profile",
      "privacy_settings", "public_url_enabled", "profile_tier", "completion_percent",
      "created_at",
    ];

    const vals = [
      sqlStr(gahoiId),
      sqlStr(name), sqlStr(get(row, "Father")), sqlStr(get(row, "Mobile")), sqlStr(get(row, "Email")),
      sqlStr(get(row, "Profession")), sqlStr(get(row, "Designation")), sqlStr(get(row, "Address")),
      sqlStr(get(row, "City")), sqlStr(get(row, "Pincode")), sqlStr(get(row, "Native")), sqlStr(get(row, "Akna")),
      sqlStr(sanitizeMMDD(get(row, "Birthday"))), sqlStr(sanitizeMMDD(get(row, "Anniversary"))), sqlStr(get(row, "Status") || "Pending"),
      sqlStr(get(row, "Role")), sqlStr(get(row, "Marital") || "Unmarried"), sqlStr(get(row, "Spouse")),
      sqlStr(get(row, "ShowMobile") || "yes"), sqlArray(get(row, "Keywords")), sqlStr(get(row, "Photo")),
      sqlStr(get(row, "BloodGroup")), sqlStr(get(row, "ReferredBy")), sqlStr(get(row, "ApprovedBy")),
      get(row, "ApprovedAt") ? sqlStr(get(row, "ApprovedAt")) : "NULL", sqlJsonb(profile),
      sqlJsonb(privacySettings), sqlBool(get(row, "PublicUrlEnabled")),
      sqlStr(get(row, "ProfileTier") || "Bronze"), get(row, "CompletionPercent") || "0",
      get(row, "Timestamp") ? sqlStr(get(row, "Timestamp")) : "now()",
    ];

    console.log(
      `insert into persons (${cols.join(", ")}) values (${vals.join(", ")}) on conflict (gahoi_id) do nothing;`,
    );
  });

  console.error(`\n✅ ${dataRows.length - skipped} rows converted, ${skipped} खाली rows छोड़े गए।`);
  console.error("⚠️  ज़रूरी बाद का कदम: पुराने GahoiId बरकरार रखे गए हैं (जहाँ मौजूद थे) —");
  console.error("   migration के बाद ये ज़रूर चलाएं ताकि नए registrations से टकराव ना हो:");
  console.error("   select setval('gahoi_id_seq', (select max(substring(gahoi_id from 3)::int) from persons));");
}

main();
